name: Scheduled Script

on:
  schedule:
    - cron: '10 * * * *'

jobs:
  run-script:
    name: job0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
            PASSWORD: ${{ secrets.PASSWORD }}
      run: python main.py