name: Scheduled Script

on:
  schedule:
    - cron: '10 * * * *'
  push:
    branches: [ "main" ]

jobs:
  run-script:
    name: job0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - env:
            PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        pip install webdavclient3==3.14.5
        python main.py